apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-linker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-linker
  template:
    metadata:
      labels:
        name: kube-linker
    spec:
      serviceAccountName: kube-linker
      containers:
        - name: kube-linker
          image: vkfont/kube-linker:0.0.1
          command:
          - kube-linker
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
            name: http
            protocol: TCP
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kube-linker"
