apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-linker
rules:
- apiGroups:
  - ""
  # resourceNames:
  # - kube-linker-lock
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  # - namespaces
  - pods
  verbs:
  - get
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - services
#   - services/finalizers
#   - endpoints
#   - persistentvolumeclaims
#   - events
#   - configmaps
#   - secrets
#   verbs:
#   - '*'
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - replicasets
#   - statefulsets
#   verbs:
#   - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
# - apiGroups:
#   - apps
#   resourceNames:
#   - kube-linker
#   resources:
#   - deployments/finalizers
#   verbs:
#   - update
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   verbs:
#   - get
# - apiGroups:
#   - apps
#   resources:
#   - replicasets
#   verbs:
#   - get
# - apiGroups:
#   - kube-linker
#   resources:
#   - '*'
#   verbs:
#   - '*'
