kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-linker
subjects:
- kind: ServiceAccount
  name: kube-linker
  namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: kube-linker
  apiGroup: rbac.authorization.k8s.io
