kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-linker
subjects:
- kind: ServiceAccount
  name: kube-linker
roleRef:
  kind: Role
  name: kube-linker
  apiGroup: rbac.authorization.k8s.io
